# Generated by Django 5.1.4 on 2024-12-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='cost',
            new_name='purchasing_cost',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='selling_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
