# Generated by Django 5.1.4 on 2025-01-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='date',
        ),
    ]
