# Generated by Django 5.1.4 on 2025-01-17 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 17, 12, 0)),
            preserve_default=False,
        ),
    ]
