# Generated by Django 5.1.4 on 2025-01-17 15:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0002_rename_cost_inventoryitem_purchasing_cost_and_more'),
        ('sales', '0005_alter_saleitem_quantity_alter_saleitem_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='total_paid',
            new_name='paid',
        ),
        migrations.RenameField(
            model_name='salepayment',
            old_name='amount',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='salepayment',
            old_name='date',
            new_name='payment_date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_price',
        ),
        migrations.AddField(
            model_name='sale',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='quantity_sold',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='selling_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salepayment',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
    ]
