# Generated by Django 5.1.4 on 2025-01-17 16:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('categories', '0001_initial'),
        ('sales', '0006_rename_total_paid_sale_paid_and_more'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='selling_cost',
            new_name='price_per_item',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='quantity_sold',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='salepayment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='salepayment',
            name='payment',
        ),
        migrations.AddField(
            model_name='sale',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='sale',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='is_fully_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='units.unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salepayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
