# Generated by Django 5.1.4 on 2025-01-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_rename_selling_cost_sale_price_per_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='quantity',
            new_name='quantity_sold',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='price_per_item',
            new_name='selling_price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='is_fully_paid',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='unit',
        ),
        migrations.AddField(
            model_name='sale',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='balance',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
